// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLZwB52N6ZVYXEMvC0jYQgWTotSlzkG4A',
    appId: '1:434629058750:web:8118f11febdbe0945dbeef',
    messagingSenderId: '434629058750',
    projectId: 'jv-maps-2026-app',
    authDomain: 'jv-maps-2026-app.firebaseapp.com',
    storageBucket: 'jv-maps-2026-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1c55JzgD_cCpqOoPqpklvG9tSHNgaFI',
    appId: '1:434629058750:android:8b68cab0278b6c325dbeef',
    messagingSenderId: '434629058750',
    projectId: 'jv-maps-2026-app',
    storageBucket: 'jv-maps-2026-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6mNQ5UtscZo9--Sk_a841AHziS0PU4Ds',
    appId: '1:434629058750:ios:e812073072b6e73f5dbeef',
    messagingSenderId: '434629058750',
    projectId: 'jv-maps-2026-app',
    storageBucket: 'jv-maps-2026-app.firebasestorage.app',
    iosBundleId: 'com.example.geoSocialApp',
  );
}
